# -*- coding: utf-8 -*-
"""Predicy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11UAn9unEbVUfx82MPu46FYxp1KO_i4i1
"""

from keras.preprocessing import image
from keras.models import load_model
import numpy as np

# Loading our own trained model
model = load_model('/content/drive/MyDrive/Colab Notebooks/your_model.h5')

# Loading and preprocessing the image for prediction
img_path = '/content/drive/MyDrive/Colab Notebooks/real_0.jpg'  # Change this to the path of your test image
img = image.load_img(img_path, target_size=(299, 299))
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
img_array /= 255.  # Normalize the image

# Making predictions
predictions = model.predict(img_array)

# Printing the predicted probability
print(f"Predicted Probability: {predictions[0]}")

# Getting the predicted class
predicted_class = int(predictions[0] > 0.5)

# Printing the predicted class
if predicted_class == 1:
    print("The image is predicted to be a deepfake.")
else:
    print("The image is predicted to be real.")
